name: flutter_lab
description: Laboratorio Flutter v1 para practicar MVVM, feature-first y Riverpod.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
