version: 2
updates:
  - package-ecosystem: npm
    directory: /platform
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      non-major:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - platform
    commit-message:
      prefix: chore(platform)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    groups:
      non-major:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: chore(ci)
